// wlwin.h: ftrd-stream's window mode (M4). The stream as an ordinary Wayland window on the
// Frame's desktop (the nested KWin), so Frametop treats it like any app: it can float in its own
// panel (move, resize, pins, profiles), and Frametop's pointer, keyboard and input relay reach it.
//
//   - Each decoder capture buffer (NV12, linear) becomes a wl_buffer once (linux-dmabuf); a
//     decoded frame is attached as is: no copy and no GPU pass here, KWin converts while it
//     composites. The buffer goes back to the decoder when KWin releases it.
//   - wp_viewporter scales the stream to the window's size (the user resizes the window).
//   - wl_pointer -> absolute mouse / buttons / scroll on the PC; wl_keyboard (evdev codes) ->
//     Windows VK codes with modifiers.
//   - Every Wayland call happens on the main thread (WlRun); the decoder thread hands frames over
//     with WlQueueFrame (a queue and an eventfd).
// Needs: wayland-client and protocol code generated by build.sh (xdg-shell, linux-dmabuf,
// viewporter, xdg-decoration).
#pragma once
#include <linux/input-event-codes.h>
#include <sys/eventfd.h>
#include <wayland-client.h>

#include <deque>

#include "linux-dmabuf-v1-client-protocol.h"
#include "viewporter-client-protocol.h"
#include "xdg-decoration-unstable-v1-client-protocol.h"
#include "xdg-shell-client-protocol.h"

namespace {

struct WlFrame { int capIdx; int frame; };

struct Wl {
    wl_display *dpy = nullptr;
    wl_registry *reg = nullptr;
    wl_compositor *comp = nullptr;
    xdg_wm_base *wm = nullptr;
    zwp_linux_dmabuf_v1 *dmabuf = nullptr;
    wp_viewporter *vp = nullptr;
    zxdg_decoration_manager_v1 *decoMgr = nullptr;
    wl_seat *seat = nullptr;
    wl_pointer *ptr = nullptr;
    wl_keyboard *kbd = nullptr;
    wl_surface *surf = nullptr;
    xdg_surface *xsurf = nullptr;
    xdg_toplevel *top = nullptr;
    wp_viewport *view = nullptr;
    bool configured = false, closed = false;
    int winW = 0, winH = 0;          // window size (logical), from configure; 0 = ours to pick
    int defW = 0, defH = 0;          // the size we pick
    int streamW = 0, streamH = 0;
    std::vector<wl_buffer *> bufs;   // per capture buffer index
    int attached = -1;               // on screen now (KWin may still hold it until release)
    std::vector<bool> held;          // KWin holds it: don't requeue until release
    // decoder thread -> main thread
    std::mutex mu;
    std::deque<WlFrame> q;
    int efd = -1;
    // input
    double px = 0, py = 0;
    int keysMods = 0;
    std::vector<int> keysDown;       // VK codes held on the PC
    uint64_t moves = 0, clicks = 0, scrolls = 0, keys = 0, commits = 0;
} g_wl;

// Decoder thread: a decoded frame is ready in capture buffer `capIdx`.
void WlQueueFrame(int capIdx, int frame) {
    {
        std::lock_guard<std::mutex> l(g_wl.mu);
        g_wl.q.push_back({capIdx, frame});
    }
    uint64_t one = 1;
    if (write(g_wl.efd, &one, sizeof one) < 0) {}
}

// ---- evdev key code -> Windows virtual-key code (US layout, as Moonlight expects) --------
int Vk(uint32_t k) {
    static const char row1[] = "QWERTYUIOP", row2[] = "ASDFGHJKL", row3[] = "ZXCVBNM";
    if (k >= KEY_1 && k <= KEY_9) return '1' + int(k - KEY_1);
    if (k == KEY_0) return '0';
    if (k >= KEY_Q && k <= KEY_P) return row1[k - KEY_Q];
    if (k >= KEY_A && k <= KEY_L) return row2[k - KEY_A];
    if (k >= KEY_Z && k <= KEY_M) return row3[k - KEY_Z];
    if (k >= KEY_F1 && k <= KEY_F10) return 0x70 + int(k - KEY_F1);
    switch (k) {
        case KEY_ESC: return 0x1B; case KEY_MINUS: return 0xBD; case KEY_EQUAL: return 0xBB;
        case KEY_BACKSPACE: return 0x08; case KEY_TAB: return 0x09; case KEY_LEFTBRACE: return 0xDB;
        case KEY_RIGHTBRACE: return 0xDD; case KEY_ENTER: return 0x0D; case KEY_LEFTCTRL: return 0xA2;
        case KEY_SEMICOLON: return 0xBA; case KEY_APOSTROPHE: return 0xDE; case KEY_GRAVE: return 0xC0;
        case KEY_LEFTSHIFT: return 0xA0; case KEY_BACKSLASH: return 0xDC; case KEY_COMMA: return 0xBC;
        case KEY_DOT: return 0xBE; case KEY_SLASH: return 0xBF; case KEY_RIGHTSHIFT: return 0xA1;
        case KEY_KPASTERISK: return 0x6A; case KEY_LEFTALT: return 0xA4; case KEY_SPACE: return 0x20;
        case KEY_CAPSLOCK: return 0x14; case KEY_NUMLOCK: return 0x90; case KEY_SCROLLLOCK: return 0x91;
        case KEY_KP7: return 0x67; case KEY_KP8: return 0x68; case KEY_KP9: return 0x69; case KEY_KPMINUS: return 0x6D;
        case KEY_KP4: return 0x64; case KEY_KP5: return 0x65; case KEY_KP6: return 0x66; case KEY_KPPLUS: return 0x6B;
        case KEY_KP1: return 0x61; case KEY_KP2: return 0x62; case KEY_KP3: return 0x63; case KEY_KP0: return 0x60;
        case KEY_KPDOT: return 0x6E; case KEY_102ND: return 0xE2; case KEY_F11: return 0x7A; case KEY_F12: return 0x7B;
        case KEY_KPENTER: return 0x0D; case KEY_RIGHTCTRL: return 0xA3; case KEY_KPSLASH: return 0x6F;
        case KEY_SYSRQ: return 0x2C; case KEY_RIGHTALT: return 0xA5; case KEY_HOME: return 0x24; case KEY_UP: return 0x26;
        case KEY_PAGEUP: return 0x21; case KEY_LEFT: return 0x25; case KEY_RIGHT: return 0x27; case KEY_END: return 0x23;
        case KEY_DOWN: return 0x28; case KEY_PAGEDOWN: return 0x22; case KEY_INSERT: return 0x2D; case KEY_DELETE: return 0x2E;
        case KEY_MUTE: return 0xAD; case KEY_VOLUMEDOWN: return 0xAE; case KEY_VOLUMEUP: return 0xAF;
        case KEY_PAUSE: return 0x13; case KEY_LEFTMETA: return 0x5B; case KEY_RIGHTMETA: return 0x5C;
        case KEY_COMPOSE: return 0x5D;
        default: return 0;
    }
}
int ModBit(int vk) {
    switch (vk) {
        case 0xA0: case 0xA1: return MODIFIER_SHIFT;
        case 0xA2: case 0xA3: return MODIFIER_CTRL;
        case 0xA4: case 0xA5: return MODIFIER_ALT;
        case 0x5B: case 0x5C: return MODIFIER_META;
        default: return 0;
    }
}
void WlReleaseKeys() {
    for (int vk : g_wl.keysDown) LiSendKeyboardEvent(short(0x8000 | vk), KEY_ACTION_UP, 0);
    g_wl.keysDown.clear();
    g_wl.keysMods = 0;
}

// ---- listeners ---------------------------------------------------------------------------
void PtrEnter(void *, wl_pointer *, uint32_t, wl_surface *, wl_fixed_t x, wl_fixed_t y) {
    g_wl.px = wl_fixed_to_double(x), g_wl.py = wl_fixed_to_double(y);
}
void PtrLeave(void *, wl_pointer *, uint32_t, wl_surface *) {
    for (int b : {BUTTON_LEFT, BUTTON_RIGHT, BUTTON_MIDDLE, BUTTON_X1, BUTTON_X2})
        LiSendMouseButtonEvent(BUTTON_ACTION_RELEASE, b);
}
void PtrMotion(void *, wl_pointer *, uint32_t, wl_fixed_t x, wl_fixed_t y) {
    g_wl.px = wl_fixed_to_double(x), g_wl.py = wl_fixed_to_double(y);
    const int w = g_wl.winW ? g_wl.winW : g_wl.defW, h = g_wl.winH ? g_wl.winH : g_wl.defH;
    if (w <= 0 || h <= 0) return;
    const int sx = std::clamp(int(g_wl.px * g_wl.streamW / w), 0, g_wl.streamW - 1);
    const int sy = std::clamp(int(g_wl.py * g_wl.streamH / h), 0, g_wl.streamH - 1);
    LiSendMousePositionEvent(short(sx), short(sy), short(g_wl.streamW), short(g_wl.streamH));
    ++g_wl.moves;
}
void PtrButton(void *, wl_pointer *, uint32_t, uint32_t, uint32_t button, uint32_t state) {
    int b = 0;
    switch (button) {
        case BTN_LEFT: b = BUTTON_LEFT; break;
        case BTN_RIGHT: b = BUTTON_RIGHT; break;
        case BTN_MIDDLE: b = BUTTON_MIDDLE; break;
        case BTN_SIDE: b = BUTTON_X1; break;
        case BTN_EXTRA: b = BUTTON_X2; break;
        default: return;
    }
    const bool down = state == WL_POINTER_BUTTON_STATE_PRESSED;
    LiSendMouseButtonEvent(down ? BUTTON_ACTION_PRESS : BUTTON_ACTION_RELEASE, b);
    if (down) ++g_wl.clicks;
}
void PtrAxis(void *, wl_pointer *, uint32_t, uint32_t axis, wl_fixed_t value) {
    // Wayland: positive = down/right, ~15 units a notch (ft-screens sends 15 per notch).
    // Moonlight: positive = up/right, 120 a notch.
    const double v = wl_fixed_to_double(value);
    const int amount = int(std::lround(v * 120.0 / 15.0));
    if (!amount) return;
    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) LiSendHighResScrollEvent(short(std::clamp(-amount, -32000, 32000)));
    else LiSendHighResHScrollEvent(short(std::clamp(amount, -32000, 32000)));
    ++g_wl.scrolls;
}
void PtrFrame(void *, wl_pointer *) {}
void PtrAxisSource(void *, wl_pointer *, uint32_t) {}
void PtrAxisStop(void *, wl_pointer *, uint32_t, uint32_t) {}
void PtrAxisDiscrete(void *, wl_pointer *, uint32_t, int32_t) {}
const wl_pointer_listener kPtr = {PtrEnter, PtrLeave, PtrMotion, PtrButton, PtrAxis, PtrFrame,
                                  PtrAxisSource, PtrAxisStop, PtrAxisDiscrete};

void KbKeymap(void *, wl_keyboard *, uint32_t, int32_t fd, uint32_t) { close(fd); }
void KbEnter(void *, wl_keyboard *, uint32_t, wl_surface *, wl_array *) {}
void KbLeave(void *, wl_keyboard *, uint32_t, wl_surface *) { WlReleaseKeys(); }  // nothing stays held
void KbKey(void *, wl_keyboard *, uint32_t, uint32_t, uint32_t key, uint32_t state) {
    const int vk = Vk(key);
    if (!vk) return;
    const bool down = state == WL_KEYBOARD_KEY_STATE_PRESSED;
    const int mb = ModBit(vk);
    if (down) {
        if (mb) g_wl.keysMods |= mb;
        if (std::find(g_wl.keysDown.begin(), g_wl.keysDown.end(), vk) == g_wl.keysDown.end()) g_wl.keysDown.push_back(vk);
    } else {
        g_wl.keysDown.erase(std::remove(g_wl.keysDown.begin(), g_wl.keysDown.end(), vk), g_wl.keysDown.end());
        if (mb) {
            g_wl.keysMods = 0;
            for (int v : g_wl.keysDown) g_wl.keysMods |= ModBit(v);
        }
    }
    LiSendKeyboardEvent(short(0x8000 | vk), down ? KEY_ACTION_DOWN : KEY_ACTION_UP, char(g_wl.keysMods));
    if (down) ++g_wl.keys;
}
void KbMods(void *, wl_keyboard *, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t) {}
void KbRepeat(void *, wl_keyboard *, int32_t, int32_t) {}
const wl_keyboard_listener kKbd = {KbKeymap, KbEnter, KbLeave, KbKey, KbMods, KbRepeat};

void SeatCaps(void *, wl_seat *seat, uint32_t caps) {
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !g_wl.ptr)
        g_wl.ptr = wl_seat_get_pointer(seat), wl_pointer_add_listener(g_wl.ptr, &kPtr, nullptr);
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !g_wl.kbd)
        g_wl.kbd = wl_seat_get_keyboard(seat), wl_keyboard_add_listener(g_wl.kbd, &kKbd, nullptr);
}
void SeatName(void *, wl_seat *, const char *) {}
const wl_seat_listener kSeat = {SeatCaps, SeatName};

void WmPing(void *, xdg_wm_base *wm, uint32_t serial) { xdg_wm_base_pong(wm, serial); }
const xdg_wm_base_listener kWm = {WmPing};

void XsConfigure(void *, xdg_surface *xs, uint32_t serial) {
    xdg_surface_ack_configure(xs, serial);
    g_wl.configured = true;
    const int w = g_wl.winW ? g_wl.winW : g_wl.defW, h = g_wl.winH ? g_wl.winH : g_wl.defH;
    if (g_wl.view && w > 0 && h > 0) wp_viewport_set_destination(g_wl.view, w, h);
    wl_surface_commit(g_wl.surf);
}
const xdg_surface_listener kXs = {XsConfigure};

void TopConfigure(void *, xdg_toplevel *, int32_t w, int32_t h, wl_array *) {
    if (w > 0 && h > 0 && (w != g_wl.winW || h != g_wl.winH)) {
        g_wl.winW = w, g_wl.winH = h;
        printf("window: %dx%d\n", w, h);
    }
}
void TopClose(void *, xdg_toplevel *) { g_wl.closed = true; }
void TopBounds(void *, xdg_toplevel *, int32_t, int32_t) {}
void TopCaps(void *, xdg_toplevel *, wl_array *) {}
const xdg_toplevel_listener kTop = {TopConfigure, TopClose, TopBounds, TopCaps};

void BufRelease(void *data, wl_buffer *) {
    const int i = int(reinterpret_cast<intptr_t>(data));
    if (i >= 0 && i < int(g_wl.held.size()) && g_wl.held[size_t(i)]) {
        g_wl.held[size_t(i)] = false;
        QueueCap(g_D, i);
    }
}
const wl_buffer_listener kBuf = {BufRelease};

void RegGlobal(void *, wl_registry *r, uint32_t name, const char *iface, uint32_t ver) {
    const std::string i = iface;
    if (i == wl_compositor_interface.name) g_wl.comp = static_cast<wl_compositor *>(wl_registry_bind(r, name, &wl_compositor_interface, std::min(ver, 4u)));
    else if (i == xdg_wm_base_interface.name) g_wl.wm = static_cast<xdg_wm_base *>(wl_registry_bind(r, name, &xdg_wm_base_interface, std::min(ver, 2u)));
    else if (i == zwp_linux_dmabuf_v1_interface.name) g_wl.dmabuf = static_cast<zwp_linux_dmabuf_v1 *>(wl_registry_bind(r, name, &zwp_linux_dmabuf_v1_interface, std::min(ver, 3u)));
    else if (i == wp_viewporter_interface.name) g_wl.vp = static_cast<wp_viewporter *>(wl_registry_bind(r, name, &wp_viewporter_interface, 1));
    else if (i == zxdg_decoration_manager_v1_interface.name) g_wl.decoMgr = static_cast<zxdg_decoration_manager_v1 *>(wl_registry_bind(r, name, &zxdg_decoration_manager_v1_interface, 1));
    else if (i == wl_seat_interface.name) g_wl.seat = static_cast<wl_seat *>(wl_registry_bind(r, name, &wl_seat_interface, std::min(ver, 5u)));
}
void RegRemove(void *, wl_registry *, uint32_t) {}
const wl_registry_listener kReg = {RegGlobal, RegRemove};

// ---- setup / frames ------------------------------------------------------------------------
bool WlInit(int streamW, int streamH, int winW, int winH) {
    g_wl.streamW = streamW, g_wl.streamH = streamH, g_wl.defW = winW, g_wl.defH = winH;
    g_wl.dpy = wl_display_connect(nullptr);
    if (!g_wl.dpy) return fprintf(stderr, "window: can't connect to WAYLAND_DISPLAY=%s\n", getenv("WAYLAND_DISPLAY") ?: "(unset)"), false;
    g_wl.reg = wl_display_get_registry(g_wl.dpy);
    wl_registry_add_listener(g_wl.reg, &kReg, nullptr);
    wl_display_roundtrip(g_wl.dpy);
    if (!g_wl.comp || !g_wl.wm || !g_wl.dmabuf || !g_wl.vp)
        return fprintf(stderr, "window: compositor lacks xdg-shell / linux-dmabuf / viewporter\n"), false;
    xdg_wm_base_add_listener(g_wl.wm, &kWm, nullptr);
    if (g_wl.seat) wl_seat_add_listener(g_wl.seat, &kSeat, nullptr);
    g_wl.surf = wl_compositor_create_surface(g_wl.comp);
    g_wl.view = wp_viewporter_get_viewport(g_wl.vp, g_wl.surf);
    g_wl.xsurf = xdg_wm_base_get_xdg_surface(g_wl.wm, g_wl.surf);
    xdg_surface_add_listener(g_wl.xsurf, &kXs, nullptr);
    g_wl.top = xdg_surface_get_toplevel(g_wl.xsurf);
    xdg_toplevel_add_listener(g_wl.top, &kTop, nullptr);
    xdg_toplevel_set_title(g_wl.top, "Remote PC");
    xdg_toplevel_set_app_id(g_wl.top, "org.frametop.RemoteDisplay");
    if (g_wl.decoMgr) {
        auto *d = zxdg_decoration_manager_v1_get_toplevel_decoration(g_wl.decoMgr, g_wl.top);
        zxdg_toplevel_decoration_v1_set_mode(d, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
    }
    wl_surface_commit(g_wl.surf);
    g_wl.efd = eventfd(0, EFD_CLOEXEC | EFD_NONBLOCK);
    wl_display_roundtrip(g_wl.dpy);
    printf("window: connected to %s, default size %dx%d\n", getenv("WAYLAND_DISPLAY") ?: "wayland-0", winW, winH);
    return true;
}

wl_buffer *WlBufferFor(int i) {
    if (int(g_wl.bufs.size()) <= i) g_wl.bufs.resize(size_t(i) + 1, nullptr), g_wl.held.resize(size_t(i) + 1, false);
    if (g_wl.bufs[size_t(i)]) return g_wl.bufs[size_t(i)];
    const auto &pm = g_D.capFmt.fmt.pix_mp;
    const uint32_t stride = pm.plane_fmt[0].bytesperline;
    auto *params = zwp_linux_dmabuf_v1_create_params(g_wl.dmabuf);
    zwp_linux_buffer_params_v1_add(params, g_D.cap[size_t(i)].fd[0], 0, 0, stride, 0, 0);
    zwp_linux_buffer_params_v1_add(params, g_D.cap[size_t(i)].fd[0], 1, stride * pm.height, stride, 0, 0);
    wl_buffer *b = zwp_linux_buffer_params_v1_create_immed(params, int(g_D.visible.width), int(g_D.visible.height),
                                                           DRM_FORMAT_NV12, 0);
    zwp_linux_buffer_params_v1_destroy(params);
    wl_buffer_add_listener(b, &kBuf, reinterpret_cast<void *>(intptr_t(i)));
    g_wl.bufs[size_t(i)] = b;
    return b;
}

// Main thread: show the newest queued frame; give older ones straight back to the decoder.
void WlFrames(std::function<void(int frame)> shown) {
    uint64_t n;
    if (read(g_wl.efd, &n, sizeof n) < 0) {}
    std::deque<WlFrame> q;
    {
        std::lock_guard<std::mutex> l(g_wl.mu);
        q.swap(g_wl.q);
    }
    if (q.empty()) return;
    while (q.size() > 1) QueueCap(g_D, q.front().capIdx), q.pop_front();
    const WlFrame f = q.front();
    if (!g_wl.configured) { QueueCap(g_D, f.capIdx); return; }
    wl_buffer *b = WlBufferFor(f.capIdx);
    g_wl.held[size_t(f.capIdx)] = true;
    wl_surface_attach(g_wl.surf, b, 0, 0);
    wl_surface_damage_buffer(g_wl.surf, 0, 0, INT32_MAX, INT32_MAX);
    const int w = g_wl.winW ? g_wl.winW : g_wl.defW, h = g_wl.winH ? g_wl.winH : g_wl.defH;
    wp_viewport_set_destination(g_wl.view, w, h);
    wl_surface_commit(g_wl.surf);
    wl_display_flush(g_wl.dpy);
    g_wl.attached = f.capIdx;
    ++g_wl.commits;
    shown(f.frame);
}

// Main thread: wait up to timeoutMs for Wayland events or frames, and handle them.
void WlPoll(int timeoutMs, std::function<void(int frame)> shown) {
    while (wl_display_prepare_read(g_wl.dpy) != 0) wl_display_dispatch_pending(g_wl.dpy);
    wl_display_flush(g_wl.dpy);
    pollfd p[2] = {{wl_display_get_fd(g_wl.dpy), POLLIN, 0}, {g_wl.efd, POLLIN, 0}};
    if (poll(p, 2, timeoutMs) > 0 && (p[0].revents & POLLIN)) wl_display_read_events(g_wl.dpy);
    else wl_display_cancel_read(g_wl.dpy);
    wl_display_dispatch_pending(g_wl.dpy);
    if (p[1].revents & POLLIN) WlFrames(shown);
}

}  // namespace
